[package]
name = "vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curv-kzen = "0.9"
sha2 = "0.9"
curve25519-dalek = "3"
rand = "0.7"